"""rename comments to comment

Revision ID: db39d94442a9
Revises: 5166f0095fb1
Create Date: 2024-07-03 09:24:09.880572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db39d94442a9'
down_revision = '5166f0095fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('reviews', 'comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comments', sa.VARCHAR(), nullable=True))
    op.drop_column('reviews', 'comment')
    # ### end Alembic commands ###
